services:
  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3,logs,cloudwatch
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - PERSISTENCE=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
